@hostname = http://playbox:5160

### Create order
POST {{hostname}}/gateway/orders
Content-Type: application/json

{
    "Item": "Product 1",
    "Quantity": 1,
    "Amount": 3,
    "PaymentMethod": "CreditCard",
    "Address": "address 1"
}

### Get last 5 order
GET {{hostname}}/gateway/orders?top=5

### Get last 5 payment
GET {{hostname}}/gateway/payments?top=5

### Add stock item
POST {{hostname}}/gateway/items
Content-Type: application/json

{
    "Item": "Product 1",
    "Quantity": 1
}

### Get stock item
GET {{hostname}}/gateway/items/Product%201

### Get top 5 stock items
GET {{hostname}}/gateway/items?top=5

### Get last 5 delivery
GET {{hostname}}/gateway/deliveries?top=5
