### Create stock item
POST http://127.0.0.1:5002/addItem
Content-Type: application/json

{
    "Item": "Product 1",
    "Quantity": 100
}

### Get stock item
GET http://127.0.0.1:5002/getItem/Product%201
